version = 0.1

[default]
[default.global.parameters]
stack_name = "originless-cloudfront-cf2"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
stack_name = "originless-cloudfront-cf2-dev"
s3_bucket = "YOUR_S3_BUCKET_NAME"
s3_prefix = "originless-cloudfront-cf2/dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true

[default.package.parameters]
s3_bucket = "YOUR_S3_BUCKET_NAME"
s3_prefix = "originless-cloudfront-cf2/dev"
region = "us-east-1"

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
